<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE AutoXlet [
<!ELEMENT AutoXlet (Xlet+)>
<!ELEMENT Xlet (RCEvent+)>
	<!ATTLIST Xlet 
	name CDATA #REQUIRED
	orgID CDATA #REQUIRED
	appID CDATA #REQUIRED
	pauseAfterLast CDATA #IMPLIED>
<!ELEMENT RCEvent (#PCDATA)>
	<!ATTLIST RCEvent 
	name CDATA #IMPLIED
	pauseBeforeNext CDATA #IMPLIED
	monitorTimeout CDATA #IMPLIED
	getResultsAfter (true|false) #IMPLIED>
<!ELEMENT Repeat (RCEvent+)>
    <!ATTLIST Repeat
    count CDATA #REQUIRED>
]>
<AutoXlet>
	
        <!-- OCPERF_INB_CONC_PREFETCH -->
	<Xlet name="OCPERF_INB_CONC_PREFETCH" orgID="0x1" appID="0x7300" pauseAfterLast="100000" startupTimeout="1000000">
	</Xlet>

        <!-- OCPERF_INB_SEQ_NSAP -->
	<Xlet name="OCPERF_INB_SEQ_NSAP" orgID="0x1" appID="0x7301" pauseAfterLast="100000" startupTimeout="1000000">
	</Xlet>

        <!-- CPERF_OOB_SEQ -->
	<Xlet name="CPERF_OOB_SEQ" orgID="0x1" appID="0x7302" pauseAfterLast="100000" startupTimeout="1000000">
	</Xlet>

        <!-- OCPERF_OOB_CONC_NSAP_PREFETCH -->
	<Xlet name="OCPERF_OOB_CONC_NSAP_PREFETCH" orgID="0x1" appID="0x7323" pauseAfterLast="100000" startupTimeout="1000000">
	</Xlet>

</AutoXlet>
