=== amirna2/OCAP-RI/RI_Stack/apps/qa/org/cablelabs/xlet/VideoPresentationTest/configSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cablelabs.org/VideoPresentationTest/configSchema" xmlns:tns="http://www.cablelabs.org/VideoPresentationTest/configSchema">
	<element name="configurations">
		<complexType>
			<sequence>
				<element name="vc" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="source" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="result" maxOccurs="unbounded">
											<complexType>
												<sequence>
													<element name="ava" maxOccurs="1" minOccurs="1">
														<complexType>
															<attribute name="xPosition" use="required" type="float" />
															<attribute name="yPosition" use="required" type="float" />
															<attribute name="width" use="required" type="float" />
															<attribute name="height" use="required" type="float" />
														</complexType>
													</element>
													<element name="tva" maxOccurs="1" minOccurs="1">
														<complexType>
															<attribute name="xPosition" use="required" type="float" />
															<attribute name="yPosition" use="required" type="float" />
															<attribute name="width" use="required" type="float" />
															<attribute name="height" use="required" type="float" />
														</complexType>
													</element>
													<element name="avaos" maxOccurs="1" minOccurs="1">
														<complexType>
															<attribute name="xPosition" use="required" type="float" />
															<attribute name="yPosition" use="required" type="float" />
															<attribute name="width" use="required" type="float" />
															<attribute name="height" use="required" type="float" />
														</complexType>
													</element>
													<element name="tvaos" maxOccurs="1" minOccurs="1">
														<complexType>
															<attribute name="xPosition" use="required" type="float" />
															<attribute name="yPosition" use="required" type="float" />
															<attribute name="width" use="required" type="float" />
															<attribute name="height" use="required" type="float" />
														</complexType>
													</element>
												</sequence>
												<attribute name="dfc" use="required">
													<simpleType>
														<restriction base="string">
															<enumeration value="DFC_PROCESSING_FULL" />
															<enumeration value="DFC_PROCESSING_LB_16_9" />
															<enumeration value="DFC_PROCESSING_LB_14_9" />
															<enumeration value="DFC_PROCESSING_CCO" />
															<enumeration value="DFC_PROCESSING_PAN_SCAN" />
															<enumeration value="DFC_PROCESSING_LB_2_21_1_ON_4_3" />
															<enumeration value="DFC_PROCESSING_LB_2_21_1_ON_16_9" />
															<enumeration value="DFC_PLATFORM" />
															<enumeration value="DFC_PROCESSING_16_9_ZOOM" />
														</restriction>
													</simpleType>
												</attribute>
											</complexType>
										</element>
									</sequence>
									<attribute name="sourceId" type="string" use="required" />
									<attribute name="afd" use="required">
										<simpleType>
											<restriction base="string">
												<enumeration value="AFD_NOT_PRESENT" />
												<enumeration value="AFD_16_9_TOP" />
												<enumeration value="AFD_14_9_TOP" />
												<enumeration value="AFD_GT_16_9" />
												<enumeration value="AFD_SAME" />
												<enumeration value="AFD_4_3" />
												<enumeration value="AFD_16_9" />
												<enumeration value="AFD_14_9" />
												<enumeration value="AFD_4_3_SP_14_9" />
												<enumeration value="AFD_16_9_SP_14_9" />
												<enumeration value="AFD_16_9_SP_4_3" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="ar" use="required">
										<simpleType>
											<restriction base="string">
												<enumeration value="ASPECT_RATIO_UNKNOWN" />
												<enumeration value="ASPECT_RATIO_4_3" />
												<enumeration value="ASPECT_RATIO_16_9" />
												<enumeration value="ASPECT_RATIO_2_21_1" />
											</restriction>
										</simpleType>
									</attribute>
								</complexType>
							</element>
						</sequence>
						<attribute name="parHeight" />
						<attribute name="parWidth" />
						<attribute name="scrWidth" />
						<attribute name="scrHeight" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>




</schema>

=== amirna2/OCAP-RI/RI_Stack/apps/qa/org/cablelabs/xlet/VideoPresentationTest/dsmConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configurations xmlns:tns="http://www.cablelabs.org/VideoPresentationTest/configSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cablelabs.org/VideoPresentationTest/configSchema configSchema.xsd ">
	<!-- DSM configurations (config settings for DesMoines head-end) -->
    <vc parHeight="1" parWidth="1" scrHeight="1080" scrWidth="1920">
    	<source afd="AFD_16_9" ar="ASPECT_RATIO_16_9" sourceId="0x50a">
    		<result dfc="DFC_PLATFORM">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    		<result dfc="DFC_PROCESSING_FULL">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
		</source>
    	<source afd="AFD_4_3" ar="ASPECT_RATIO_4_3" sourceId="0x4b0">
    		<result dfc="DFC_PLATFORM">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    		<result dfc="DFC_PROCESSING_16_9_ZOOM">
    			<ava height="1.3333" width="1.0" xPosition="0.0" yPosition="-0.1666" />
	    		<tva height="1.3333" width="1.0" xPosition="0.0" yPosition="-0.1666" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    	</source>
    </vc>
    <vc parHeight="1" parWidth="1" scrHeight="720" scrWidth="1280">
		<source afd="AFD_16_9" ar="ASPECT_RATIO_16_9" sourceId="0x50a">
    		<result dfc="DFC_PLATFORM">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    		<result dfc="DFC_PROCESSING_FULL">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
		</source>
		<source afd="AFD_4_3" ar="ASPECT_RATIO_4_3" sourceId="0x4b0">
    		<result dfc="DFC_PLATFORM">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    		<result dfc="DFC_PROCESSING_16_9_ZOOM">
    			<ava height="1.3333" width="1.0" xPosition="0.0" yPosition="-0.1666" />
	    		<tva height="1.3333" width="1.0" xPosition="0.0" yPosition="-0.1666" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    	</source>
    </vc>
   	<vc parHeight="1" parWidth="1" scrHeight="480" scrWidth="640">
		<source afd="AFD_16_9" ar="ASPECT_RATIO_16_9" sourceId="0x50a">
    		<result dfc="DFC_PLATFORM">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    		<result dfc="DFC_PROCESSING_LB_16_9">
    			<ava height="0.75" width="1.0" xPosition="0.0" yPosition="0.125" />
	    		<tva height="0.75" width="1.0" xPosition="0.0" yPosition="0.125" />
    			<avaos height="0.75" width="1.0" xPosition="0.0" yPosition="0.125" />
	    		<tvaos height="0.75" width="1.0" xPosition="0.0"	yPosition="0.125" />
    		</result>
    		<result dfc="DFC_PROCESSING_LB_14_9">
    			<ava height="0.8571" width="1.1429" xPosition="-0.0714" yPosition="0.0714" />
	    		<tva height="0.8571" width="1.1429" xPosition="-0.0714" yPosition="0.0714" />
    			<avaos height="0.8571" width="1.0" xPosition="0.0"	yPosition="0.0714" />
	    		<tvaos height="0.8571" width="1.0" xPosition="0.0"	yPosition="0.0714" />
    		</result>
    		<result dfc="DFC_PROCESSING_CCO">
    			<ava height="1.0" width="1.3333" xPosition="-0.1666" yPosition="0.0" />
	    		<tva height="1.0" width="1.3333" xPosition="-0.1666" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
		</source>
		<source afd="AFD_4_3" ar="ASPECT_RATIO_4_3" sourceId="0x4b0">
    		<result dfc="DFC_PLATFORM">
    			<ava height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
	    		<tva height="1.0" width="1.0" xPosition="0.0" yPosition="0.0" />
    			<avaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
	    		<tvaos height="1.0" width="1.0" xPosition="0.0"	yPosition="0.0" />
    		</result>
    	</source>
    </vc>
	<!-- End DSM configurations -->
</configurations>
