=== amirna2/OCAP-RI/RI_Stack/java/test/base/org/havi/ui/port/testconfig.dtd
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Jay Tracy (Snap2 Corporation) -->
<!-- structure for organizing tests -->
<!ELEMENT TestSuite (Object*, Template*, TestClass+)>
<!ELEMENT TestClass (Test*)>
<!-- name - name of the test class -->
<!ATTLIST TestClass
	name NMTOKEN #REQUIRED
>

<!ELEMENT Test (TestCase*)>
<!-- name - name of the test -->
<!ATTLIST Test
	name NMTOKEN #REQUIRED
>

<!ELEMENT TestCase (Setup*, Input*, Result+)>
<!-- can optionally target a test case to a particular screen or device -->
<!ATTLIST TestCase
	targetType (any | screen | device) "any"
	targetId CDATA "none"
>

<!-- Main sections of a single test -->
<!ELEMENT Setup (Template?, Object?)>
<!-- command -  a string describing what this setup element is for.  The test code is responsible for recognizing 
				the command, and knowing what to do what to do with any contained template or other object.
				(example: setcurrentconfig, startvideo, setbackgroundcolor, ...)
	misc - an optional string used to further clarify the action to take, or to give more context to the  the 
			template or object
	templateId - id of a pre-defined template to use (rather than specify a new template element)
	objectId - id of a pre-defined object to use (rather than specify a new object element) -->
<!ATTLIST Setup
	command NMTOKEN #REQUIRED
	misc CDATA #IMPLIED
	templateId IDREF #IMPLIED
	objectId IDREF #IMPLIED
>

<!ELEMENT Input (Template?, Object?)>
<!-- command -  a string describing what this input element is for.  The test code is responsible for recognizing 
				the command, and knowing what to do what to do with any contained template or other object.
				(example: inputtemplate, resizetemplate, componentbounds, ...)
	misc - an optional string used to further clarify the action to take, or to give more context to the 
			template or object
	templateId - id of a pre-defined template to use (rather than specify a new template element)
	objectId - id of a pre-defined object to use (rather than specify a new object element) -->
<!ATTLIST Input
	command NMTOKEN #REQUIRED
	misc CDATA #IMPLIED
	templateId IDREF #IMPLIED
	objectId IDREF #IMPLIED
>

<!-- result data to compare against-->
<!ELEMENT Result (Template?, Object?)>
<!-- command -  a string describing what this result element is for.  The test code is responsible for recognizing 
				the command, and knowing what to do what to do with any contained template or other object.
				(example: compareequal, comparecompatible, comparelarger...)
	misc - an optional string used to further clarify the action to take, or to give more context to the 
			template or object
	templateId - id of a pre-defined template to use (rather than specify a new template element)
	objectId - id of a pre-defined object to use (rather than specify a new object element) -->
<!ATTLIST Result
	command NMTOKEN #REQUIRED
	misc CDATA #IMPLIED
	templateId IDREF #IMPLIED
	objectId IDREF #IMPLIED
>

<!-- Used to specify the exact actions/data for each section of a test. -->
<!ELEMENT Template (Preference+)>
<!-- id - optional unique id allowing the template to be reused elsewhere in the document
	type - fully qualified class name so the appropriate type of template can be constructed
	device - optional attribute (used when describing an HScreenConfigTemplate) 	specifying
			a particular HScreenDevice to use when requesting an HScreenConfiguration
			with this template. -->
<!ATTLIST Template
	id ID #IMPLIED
	type NMTOKEN #REQUIRED
	device CDATA #IMPLIED
>

<!ELEMENT Preference (Object?)>
<!-- name - preference constant name (as defined in the relevant class)
	priority - priority constant name (as defined in the relevant class)
	objectId - id of a pre-defined object to use (rather than specify a new object element)-->
<!ATTLIST Preference
	name NMTOKEN #REQUIRED
	priority NMTOKEN #REQUIRED
	objectId IDREF #IMPLIED
>

<!ELEMENT Object (Parameter*, Template?)>
<!-- type - fully qualified class name so the appropriate type of object can be constructed
	templateId - id of a pre-defined template to use (rather than specify a new template element) 
				(used in the case where the "type" attribute is a template type
	id - optional unique id allowing the object to be reused elsewhere in the document -->
<!ATTLIST Object
	type NMTOKEN #REQUIRED
	templateId IDREF #IMPLIED
	id ID #IMPLIED
>

<!-- type - fully qualified class name or primitive type name
	value - string representation of the value -->
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
	type NMTOKEN #REQUIRED
	value CDATA #REQUIRED
>

=== amirna2/OCAP-RI/RI_Stack/java/test/base/org/havi/ui/port/mpe/8300hd/testconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Jay Tracy (Snap2 Corporation) -->
<!DOCTYPE TestSuite SYSTEM "../../testconfig.dtd">
<TestSuite>
	<!-- OBJECT DEFINITIONS FOR REUSE -->
	<Object type="null" id="null"/>
	<Object type="org.havi.ui.HScreenRectangle" id="HSR_fullscreen">
		<Parameter type="float" value="0.0"/>
		<Parameter type="float" value="0.0"/>
		<Parameter type="float" value="1.0"/>
		<Parameter type="float" value="1.0"/>
	</Object>
	<Object type="org.havi.ui.HScreenDimension" id="HSD_1_1">
		<Parameter type="float" value="1.0"/>
		<Parameter type="float" value="1.0"/>
	</Object>
	<Object type="org.havi.ui.HScreenPoint" id="HSP_0_0">
		<Parameter type="float" value="0.0"/>
		<Parameter type="float" value="0.0"/>
	</Object>
	<Object type="java.awt.Dimension" id="dim_1920_1080">
		<Parameter type="int" value="1920"/>
		<Parameter type="int" value="1080"/>
	</Object>
	<Object type="java.awt.Dimension" id="dim_1280_720">
		<Parameter type="int" value="1280"/>
		<Parameter type="int" value="720"/>
	</Object>
	<Object type="java.awt.Dimension" id="dim_640_480">
		<Parameter type="int" value="640"/>
		<Parameter type="int" value="480"/>
	</Object>
	<Object type="java.awt.Point" id="point_0_0">
		<Parameter type="int" value="0"/>
		<Parameter type="int" value="0"/>
	</Object>
	<!-- TEMPLATE DEFINITIONS FOR REUSE -->
	<!-- Graphics Configurations -->
	<!-- 480i -->
	<Template type="org.havi.ui.HGraphicsConfigTemplate" id="gfx0.cfg0" device="Graphics[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
		<Preference name="MATTE_SUPPORT" priority="DONT_CARE"/>
		<Preference name="IMAGE_SCALING_SUPPORT" priority="DONT_CARE"/>
	</Template>
	<!-- 480p -->
	<Template type="org.havi.ui.HGraphicsConfigTemplate" id="gfx0.cfg1" device="Graphics[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED_NOT"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
		<Preference name="MATTE_SUPPORT" priority="DONT_CARE"/>
		<Preference name="IMAGE_SCALING_SUPPORT" priority="DONT_CARE"/>
	</Template>
	<!-- 720p -->
	<Template type="org.havi.ui.HGraphicsConfigTemplate" id="gfx0.cfg2" device="Graphics[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED_NOT"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="4"/>
				<Parameter type="int" value="3"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
		<Preference name="MATTE_SUPPORT" priority="DONT_CARE"/>
		<Preference name="IMAGE_SCALING_SUPPORT" priority="DONT_CARE"/>
	</Template>
	<!-- 1080i -->
	<Template type="org.havi.ui.HGraphicsConfigTemplate" id="gfx0.cfg2" device="Graphics[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="4"/>
				<Parameter type="int" value="3"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
		<Preference name="MATTE_SUPPORT" priority="DONT_CARE"/>
		<Preference name="IMAGE_SCALING_SUPPORT" priority="DONT_CARE"/>
	</Template>
	<!-- Video Configurations -->
	<!-- 480i -->
	<Template type="org.havi.ui.HVideoConfigTemplate" id="vid0.cfg0" device="Video[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
	</Template>
	<!-- 480p -->
	<Template type="org.havi.ui.HVideoConfigTemplate" id="vid0.cfg1" device="Video[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED_NOT"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
	</Template>
	<!-- 720p -->
	<Template type="org.havi.ui.HVideoConfigTemplate" id="vid0.cfg2" device="Video[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED_NOT"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_1280_720"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
	</Template>
	<!-- 1080i -->
	<Template type="org.havi.ui.HVideoConfigTemplate" id="vid0.cfg3" device="Video[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_1920_1080"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
	</Template>
	<!-- Background Configurations -->
	<!-- None -->
	<Template type="org.havi.ui.HBackgroundConfigTemplate" id="background1_config1" device="Background[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED_NOT"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
		<Preference name="CHANGEABLE_SINGLE_COLOR" priority="REQUIRED"/>
		<Preference name="STILL_IMAGE" priority="REQUIRED_NOT"/>
	</Template>
	<!--
	<Template type="org.havi.ui.HBackgroundConfigTemplate" id="background1_config2" device="Background[0]">
		<Preference name="FLICKER_FILTERING" priority="REQUIRED_NOT"/>
		<Preference name="INTERLACED_DISPLAY" priority="REQUIRED_NOT"/>
		<Preference name="PIXEL_ASPECT_RATIO" priority="REQUIRED">
			<Object type="java.awt.Dimension">
				<Parameter type="int" value="1"/>
				<Parameter type="int" value="1"/>
			</Object>
		</Preference>
		<Preference name="PIXEL_RESOLUTION" priority="REQUIRED" objectId="dim_640_480"/>
		<Preference name="SCREEN_RECTANGLE" priority="REQUIRED" objectId="HSR_fullscreen"/>
		<Preference name="CHANGEABLE_SINGLE_COLOR" priority="REQUIRED"/>
		<Preference name="STILL_IMAGE" priority="REQUIRED"/>
	</Template>
	-->

	<!-- START OF TEST DEFINITIONS -->
	<TestClass name="org.havi.ui.HSceneFactoryTest">
		<Test name="besttemplate">
			<TestCase>
				<!-- SUCCESS - tests pixel size required over screen size, checks calculated screen dimension, and 
						     tests that a HGraphicsConfiguration specified in the template is used if possible. -->
				<Input command="inputtemplate">
					<Template type="org.havi.ui.HSceneTemplate">
						<Preference name="GRAPHICS_CONFIGURATION" priority="REQUIRED">
							<Object type="org.havi.ui.HGraphicsConfiguration" templateId="gfx0.cfg0"/>
						</Preference>
						<Preference name="SCENE_PIXEL_DIMENSION" priority="REQUIRED" objectId="dim_640_480"/>
						<Preference name="SCENE_PIXEL_LOCATION" priority="PREFERRED" objectId="point_0_0"/>
						<Preference name="SCENE_SCREEN_DIMENSION" priority="PREFERRED" objectId="HSD_1_1"/>
						<Preference name="SCENE_SCREEN_LOCATION" priority="PREFERRED" objectId="HSP_0_0"/>
					</Template>
				</Input>
				<Result command="compareequal">
					<Template type="org.havi.ui.HSceneTemplate">
						<Preference name="GRAPHICS_CONFIGURATION" priority="REQUIRED">
							<Object type="org.havi.ui.HGraphicsConfiguration" templateId="gfx0.cfg0"/>
						</Preference>
						<Preference name="SCENE_PIXEL_DIMENSION" priority="REQUIRED" objectId="dim_640_480"/>
						<Preference name="SCENE_PIXEL_LOCATION" priority="REQUIRED" objectId="point_0_0"/>
						<Preference name="SCENE_SCREEN_DIMENSION" priority="REQUIRED">
